# .golangci.yml
version: "2"

run:
  timeout: 5m

linters:
  default: none

  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - errcheck
    - misspell
    - revive
    - whitespace
    - gocognit
    - nestif
    - dupl

  settings:
    dupl:
      threshold: 80
      
    errcheck:
      check-blank: true

    gocognit:
      min-complexity: 20

    nestif:
      min-complexity: 5

    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false

        - name: var-naming
          severity: warning
          disabled: false

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/papa0four/orkowatch

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  